# Generated by Django 2.0.3 on 2018-03-10 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of the series', max_length=255, verbose_name='Series title')),
                ('description', models.TextField(help_text='Description of the series', verbose_name='Series description')),
            ],
        ),
    ]
